#pragma once

enum JSONError
{
    ERR_NOERROR,
    ERR_EOF,
    ERR_INVALID_STRING,
    ERR_INVALID_TREE_SYNTAX,
    ERR_INVALID_OBJECT_SYNTAX,
    ERR_INVALID_BOOLEAN_SYNTAX,
    ERR_INVALID_FLOAT_SYNTAX,
    ERR_INVALID_UNICODE_LITERAL_SYNTAX,
    ERR_INVALID_ARRAY_SYNTAX,
    ERR_INVALID_NULL_SYNTAX,
    ERR_OUTPUT_BUFFER_TOO_SMALL,

    ERR_ITERATOR_INVALID_NODE,
    ERR_ITERATOR_INVALID_KEY_PTR,
    ERR_ITERATOR_INVALID_VALUE_PTR,
    ERR_ITERATOR_NO_MORE_ELEMENTS
};

